### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by taras-koval** [taras-koval/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by taraskoval8** [comment]
* https://www.facebook.com/DonaldTrump
* realDonaldTrump@whitehouse.gov

**Comment by taras-koval** [comment]
123
